checks:
  no-fixme:
    files: ["*"]
    run: "! grep -nE 'FIXME'"
  no-merge-markers:
    files: ["*"]
    run: "! grep -nE '^(<<<<<<< |=======$|>>>>>>> )'"

  ruff-check:
    files: ["**/*.py"]
    run: "ruff check --quiet --stdin-filename \"$IRONLINT_FILE\" -"
  ruff-format-check:
    files: ["**/*.py"]
    run: "ruff format --diff --stdin-filename \"$IRONLINT_FILE\" - | grep -q '^---' && exit 1 || exit 0"
  no-debug-prints:
    files: ["**/*.py"]
    run: "! grep -nE '^\\s*print\\('"
  mypy-check:
    files: ["**/*.py"]
    on: [pre-commit]
    run: "mypy --follow-imports silent $IRONLINT_FILES"
